In [1]:
import sys
import os
sys.path.append(os.path.abspath('..'))

from src.data.data_loader import (
    load_supervised_data,
    load_unsupervised_data
)

In [2]:
### loading supervised and unsupervised data
# supervised dataset
df_supervised = load_supervised_data()
# unsupervised dataset
df_unsupervised = load_unsupervised_data()

In [3]:
### supervised dataset - overview
# samples
display(df_supervised.head())
# shape
print(f'Supervised dataset shape: {df_supervised.shape}')

,UniqueID,Loan To Value,Branch ID,Age,Employment Type,DisbursalDate,State_ID,State,Employee_code_ID,Mobile Avl Flag,...,Number of Active Accounts,Number of Overdue Accounts,Current Balance Amount,Sanctioned Amount,Disbursed Amount,Instalment Amount,Number of Accounts Opened Last 6 Months,Average Account Age,Number of Inquiries,Target
0,417428,88.17,18,53,Self employed,43313,NaN,Louisiana,1998,1,...,3.0,0,63727,100984,100984,5571,1,9,0,0
1,417429,83.78,13,39,Salaried,43313,NaN,Tennessee,1998,1,...,1.0,1,103435,100000,100000,160963,0,36,0,1
2,417433,74.89,63,28,Salaried,43313,NaN,New Jersey,1998,1,...,2.0,0,120985,130600,130600,15820,1,1,0,0
3,417435,73.65,67,35,Self employed,43313,NaN,Nevada,1998,1,...,0.0,0,0,0,0,0,0,6,0,0
4,417438,83.29,16,32,Salaried,43313,NaN,Illinois,1998,1,...,2.0,0,42588,51320,51320,7916,3,4,0,0

Supervised dataset shape: (59477, 23)

In [4]:
### unsupervised dataset - overview
# samples
display(df_unsupervised.head())
# shape
print(f'Unsupervised dataset shape: {df_unsupervised.shape}')

,UniqueID,Loan To Value,Branch ID,Age,Employment Type,DisbursalDate,State_ID,State,Employee_code_ID,Mobile Avl Flag,...,Number of Active Accounts,Number of Overdue Accounts,Current Balance Amount,Sanctioned Amount,Disbursed Amount,Instalment Amount,Number of Accounts Opened Last 6 Months,Number of Delinquencies Last 6 Months,Average Account Age,Number of Inquiries
0,537409,73.23,67,33,Self employed,43369,NaN,Nevada,1998,1,...,1.0,1,27600,50200,50200,1991,0,1,13,0
1,624493,88.48,67,25,Self employed,43399,NaN,Nevada,1998,1,...,0.0,0,0,0,0,31,0,0,8,1
2,518279,89.66,67,28,Self employed,43362,NaN,Nevada,1998,1,...,0.0,0,0,0,0,1347,0,0,21,0
3,510278,71.89,67,29,Salaried,43359,NaN,Nevada,1998,1,...,1.0,0,72879,74500,74500,0,0,0,2,0
4,490213,89.56,67,27,Self employed,43348,NaN,Nevada,1998,1,...,1.0,0,-41,365384,365384,0,0,0,56,1

Unsupervised dataset shape: (59477, 23)